# Generated by Django 3.2.7 on 2021-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_studentid_student_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falcuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falcuty_id', models.CharField(max_length=200)),
            ],
        ),
    ]
