# Generated by Django 3.2.7 on 2021-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_falcuty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_spot', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parking spot')),
                ('parking_status', models.BooleanField(blank=True, null=True, verbose_name='Parking status')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentid',
        ),
        migrations.AddField(
            model_name='falcuty',
            name='falcuty_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Falcuty email'),
        ),
        migrations.AddField(
            model_name='falcuty',
            name='falcuty_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Falcuty name'),
        ),
        migrations.AddField(
            model_name='falcuty',
            name='falcuty_pass',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Falcuty password'),
        ),
        migrations.AddField(
            model_name='falcuty',
            name='falcuty_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Falcuty phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Student email'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Student id'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student name'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_pass',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student password'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Student phone'),
        ),
        migrations.AlterField(
            model_name='falcuty',
            name='falcuty_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Falcuty id'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='parking_a',
            name='falcuty_user',
            field=models.ManyToManyField(blank=True, null=True, to='main.Falcuty'),
        ),
        migrations.AddField(
            model_name='parking_a',
            name='student_user',
            field=models.ManyToManyField(blank=True, null=True, to='main.Student'),
        ),
    ]
