# Generated by Django 3.2.8 on 2021-10-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211003_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_a',
            name='falcuty_user',
        ),
        migrations.RemoveField(
            model_name='parking_a',
            name='student_user',
        ),
    ]
