# Generated by Django 3.2.8 on 2021-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211013_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_a',
            name='id',
        ),
        migrations.AlterField(
            model_name='parking_a',
            name='parking_spot',
            field=models.CharField(blank=True, default='null', max_length=20, primary_key=True, serialize=False, verbose_name='Parking spot'),
        ),
    ]
