# Generated by Django 3.2.8 on 2021-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211025_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_a',
            name='parking_spot',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parking spot'),
        ),
    ]
