# Generated by Django 3.2.8 on 2021-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_parking_a_parking_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_a',
            name='parking_status',
            field=models.BooleanField(default=False, verbose_name='Parking status'),
        ),
    ]
