# Generated by Django 3.2.7 on 2021-11-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211104_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_k',
            old_name='parking_spot',
            new_name='parkingk_spot',
        ),
        migrations.RemoveField(
            model_name='parking_k',
            name='parking_status',
        ),
        migrations.AddField(
            model_name='parking_k',
            name='parkingk_status',
            field=models.BooleanField(null=True),
        ),
    ]
