# Generated by Django 3.2.8 on 2021-11-11 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20211104_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_name_log', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_name_log', to=settings.AUTH_USER_MODEL)),
                ('parking_spot', models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spot_log', to='main.parking_a')),
                ('parking_status', models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_status_log', to='main.parking_a')),
            ],
        ),
        migrations.DeleteModel(
            name='Falcuty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
