# Generated by Django 3.2.8 on 2021-11-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_log_parking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='last_name',
        ),
    ]
