# Generated by Django 3.2.8 on 2021-11-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_log_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='parking_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
