# Generated by Django 3.2.8 on 2021-11-11 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211111_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='first_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, unique=True),
        ),
    ]
