# Generated by Django 3.2.8 on 2021-11-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211111_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='parking_status',
            new_name='currently_parked_here',
        ),
    ]
