# Generated by Django 3.2.8 on 2021-11-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_parking_status_log_currently_parked_here'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='time',
            new_name='time_parked',
        ),
        migrations.AddField(
            model_name='log',
            name='time_left',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
