# Generated by Django 3.2.8 on 2021-11-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211111_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='parking_spotK',
            field=models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spotK_log', to='main.parking_k'),
        ),
        migrations.AlterField(
            model_name='log',
            name='currently_parked_here',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='parking_spot',
            field=models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spotA_log', to='main.parking_a'),
        ),
    ]
