# Generated by Django 3.2.8 on 2021-11-11 22:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211111_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='parking_spotK',
            field=models.CharField(max_length=20, null=True, verbose_name=main.models.Parking_K),
        ),
    ]
