# Generated by Django 3.2.8 on 2021-11-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_log_parking_spotk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='parking_spotK',
        ),
    ]
