# Generated by Django 3.2.7 on 2021-11-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20211111_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_B',
            fields=[
                ('parkingb_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingb spot')),
                ('parkingb_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_C1',
            fields=[
                ('parkingc1_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingc1 spot')),
                ('parkingc1_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_C2',
            fields=[
                ('parkingc2_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingc2 spot')),
                ('parkingc2_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_D',
            fields=[
                ('parkingd_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingd spot')),
                ('parkingd_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_E1',
            fields=[
                ('parkinge1_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkinge1 spot')),
                ('parkinge1_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_E2',
            fields=[
                ('parkinge2_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkinge2 spot')),
                ('parkinge2_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_E3',
            fields=[
                ('parkinge3_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkinge3 spot')),
                ('parkinge3_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_E4',
            fields=[
                ('parkinge4_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkinge4 spot')),
                ('parkinge4_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_F',
            fields=[
                ('parkingf_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingf spot')),
                ('parkingf_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_G',
            fields=[
                ('parkingg_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingg spot')),
                ('parkingg_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_H',
            fields=[
                ('parkingh_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingh spot')),
                ('parkingh_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_I',
            fields=[
                ('parkingi_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingi spot')),
                ('parkingi_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_J',
            fields=[
                ('parkingj_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingj spot')),
                ('parkingj_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_L',
            fields=[
                ('parkingl_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingl spot')),
                ('parkingl_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_M',
            fields=[
                ('parkingm_spot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Parkingm spot')),
                ('parkingm_status', models.BooleanField(null=True)),
            ],
        ),
    ]
