# Generated by Django 3.2.8 on 2021-11-16 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_auto_20211116_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('username', 'time_parked')},
        ),
    ]
