# Generated by Django 3.2.8 on 2021-11-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20211116_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
