# Generated by Django 3.2.8 on 2021-11-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
