# Generated by Django 3.2.8 on 2021-11-16 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0035_alter_log_time_parked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_parked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spotA_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
